version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"    # Redis 서버 포트
      - "8001:8001"    # Redis Insight 포트
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes  # 데이터 지속성을 위한 설정
      - REDISTIMESERIES_ARGS=RETENTION_POLICY=20    # 시계열 데이터 보존 정책
    volumes:
      - ./local-data:/data    # 로컬 데이터 볼륨 마운트
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"  # InfluxDB 포트
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_DB=k6  # 기본 데이터베이스
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana 대시보드 포트
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123  # 기본 관리자 계정
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped

  k6:
    image: grafana/k6:latest
    container_name: k6
    depends_on:
      - influxdb
    entrypoint: ["k6", "run", "-o", "influxdb=http://influxdb:8086/k6", "/scripts/test_getAvailableSeats.js"]
    volumes:
      - ./test/k6:/scripts  # 로컬의 ./test/k6 디렉터리를 컨테이너 내부 /scripts로 마운트

